"""empty message

Revision ID: 29b64bb57363
Revises: 3a29a6b35820
Create Date: 2014-09-26 15:51:29.523899

"""

# revision identifiers, used by Alembic.
revision = '29b64bb57363'
down_revision = '3a29a6b35820'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('week', sa.Column('name', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('week', 'name')
    ### end Alembic commands ###
