"""empty message

Revision ID: 3a29a6b35820
Revises: 4e9d2111f0a0
Create Date: 2014-09-26 15:38:09.298612

"""

# revision identifiers, used by Alembic.
revision = '3a29a6b35820'
down_revision = '4e9d2111f0a0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('week_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'week_id')
    ### end Alembic commands ###
