"""empty message

Revision ID: 3e6560e90e6a
Revises: 29b64bb57363
Create Date: 2015-01-24 22:33:22.975856

"""

# revision identifiers, used by Alembic.
revision = '3e6560e90e6a'
down_revision = '29b64bb57363'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'username')
    ### end Alembic commands ###
